version: "3.3"

services:
  web:
    build: 
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes: 
      - .:/rails
    environment:
      DATABASE_HOST: db
      POSTGRES_USER: wildcat
      POSTGRES_PASSWORD: wildcat
      POSTGRES_DB: wildcat_development
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis:15-3.4-alpine
    environment:
      POSTGRES_USER: wildcat
      POSTGRES_PASSWORD: wildcat
      POSTGRES_DB: wildcat_development
    volumes:
      - ./db/10_postgis.sh:/docker-entrypoint-initdb.d/10_postgis.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d wildcat_development -U wildcat"]
      interval: 2s
      timeout: 3s
      retries: 2

