databases:
  - name: postgis
    ipAllowList: []
    databaseName: wildcat
    user: wildcat

services:
  - type: web
    name: wildcat
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
